apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: maple-ingress
  namespace: default
  annotations:
    # Tells AWS to create an Application Load Balancer
    kubernetes.io/ingress.class: alb
    # Places the ALB in Public Subnets (Internet Facing)
    alb.ingress.kubernetes.io/scheme: internet-facing
    # Critical for Fargate: Routes traffic directly to Pod IP
    alb.ingress.kubernetes.io/target-type: ip
    # Health Check (Checks if Nginx/Flask are alive)
    alb.ingress.kubernetes.io/healthcheck-path: /
spec:
  rules:
    - http:
        paths:
          # Traffic Rule 1: Requests starting with /api go to Python Backend
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 5000
          
          # Traffic Rule 2: Everything else goes to React Frontend
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80